version: "3.9"

services:
  next-app:
    build: ./app
    command: sh -c "pnpm install && pnpm build && pnpm start"
    ports:
      - "3000:3000"
    env_file:
      - ./apps/web/.env 
    networks:
      - internal
    depends_on:
      - mongodb
    volumes:
      - ./nextjs:/usr/src/app/
      - node_modules-vol:/usr/src/app/node_modules
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '6000:27017'
    volumes:
      - mongodb-vol:/data/db
    env_file:
      - ./database/.env
    networks:
      - internal
    expose:
      - "27017"

networks:
  internal:

volumes:
  node_modules-vol:
  mongodb-vol: