import { assertIsDefined } from '../helper/assert';

const MONGODB_URI = process.env.MONGODB_URI;
const MONGODB_DB = process.env.MONGODB_DB;
const MONGO_INITDB_ROOT_USERNAME = process.env.MONGO_INITDB_ROOT_USERNAME;
const MONGO_INITDB_ROOT_PASSWORD = process.env.MONGO_INITDB_ROOT_PASSWORD;
const MONGO_INITDB_DATABASE = process.env.MONGO_INITDB_DATABASE;

assertIsDefined(MONGODB_URI, 'MONGODB_URI');
assertIsDefined(MONGODB_DB, 'MONGODB_DB');
assertIsDefined(MONGO_INITDB_ROOT_USERNAME, 'MONGO_INITDB_ROOT_USERNAME');
assertIsDefined(MONGO_INITDB_ROOT_PASSWORD, 'MONGO_INITDB_ROOT_PASSWORD');
assertIsDefined(MONGO_INITDB_DATABASE, 'MONGO_INITDB_DATABASE');

export const serverEnvs = {
  MONGODB_URI,
  MONGODB_DB,
  MONGO_INITDB_ROOT_USERNAME,
  MONGO_INITDB_ROOT_PASSWORD,
  MONGO_INITDB_DATABASE,
};
